# Generated by Django 6.0.1 on 2026-01-12 17:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('editor_id', models.CharField(blank=True, help_text='ID of the clinician/editor (from auth system)', max_length=100)),
                ('editor_name', models.CharField(blank=True, help_text='Display name of the editor', max_length=200)),
                ('edited_content', models.JSONField(help_text='The edited/revised JSON content')),
                ('token_diff', models.JSONField(blank=True, default=dict, help_text='Token-level diff between original and edited')),
                ('structural_diff', models.JSONField(blank=True, default=dict, help_text='Structural/JSON diff between original and edited')),
                ('diff_stats', models.JSONField(blank=True, default=dict, help_text='Statistics about the diff (additions, deletions, change rate)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('editor_notes', models.TextField(blank=True, help_text='Notes from the editor about the changes')),
                ('reviewer_notes', models.TextField(blank=True, help_text='Notes from reviewer (if applicable)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the edit was submitted for review', null=True)),
            ],
            options={
                'verbose_name': 'Edit',
                'verbose_name_plural': 'Edits',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Machine-readable label name (e.g., hallucination, missing_risk)', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable display name', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this label indicates')),
                ('category', models.CharField(blank=True, help_text='Category grouping (e.g., accuracy, safety, style)', max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor'), ('info', 'Informational')], default='minor', help_text='Severity level of issues with this label', max_length=20)),
                ('color', models.CharField(default='#6b7280', help_text='Hex color for UI display', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier for UI', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this label is available for use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Labels',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EditLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, help_text='Notes about why this label was applied')),
                ('content_path', models.CharField(blank=True, help_text='JSON path to the relevant content section', max_length=255)),
                ('start_offset', models.IntegerField(blank=True, help_text='Start character offset in raw text', null=True)),
                ('end_offset', models.IntegerField(blank=True, help_text='End character offset in raw text', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_labels', to='reviews.edit')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_labels', to='reviews.label')),
            ],
            options={
                'verbose_name': 'Edit Label',
                'verbose_name_plural': 'Edit Labels',
                'ordering': ['-created_at'],
                'unique_together': {('edit', 'label')},
            },
        ),
        migrations.AddField(
            model_name='edit',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='edits', through='reviews.EditLabel', to='reviews.label'),
        ),
        migrations.CreateModel(
            name='LLMOutput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(help_text='Name of the LLM model (e.g., gpt-4-turbo, claude-3-opus)', max_length=100)),
                ('model_version', models.CharField(blank=True, help_text='Version or snapshot identifier', max_length=50)),
                ('output_content', models.JSONField(help_text='Structured JSON output from the LLM')),
                ('raw_response', models.TextField(blank=True, help_text='Raw text response from the LLM')),
                ('prompt_template', models.CharField(blank=True, help_text='Identifier for the prompt template used', max_length=100)),
                ('generation_params', models.JSONField(blank=True, default=dict, help_text='Parameters used for generation (temperature, max_tokens, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_outputs', to='core.document')),
            ],
            options={
                'verbose_name': 'LLM Output',
                'verbose_name_plural': 'LLM Outputs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='edit',
            name='llm_output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='reviews.llmoutput'),
        ),
    ]
