# Generated by Django 6.0.1 on 2026-01-12 17:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, help_text='Source system or origin of the document', max_length=100)),
                ('document_type', models.CharField(blank=True, help_text='Type of clinical document (e.g., session_note, intake, assessment)', max_length=50)),
                ('raw_content', models.JSONField(help_text='Raw JSON content of the clinical note')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
